### ISSUE TITLE
Some links can't be accessed by keyboard tabbing

### ISSUE THREAD

**Issue by healeycodes** [jameslittle230/rrl-3#3]
Some links can't be accessed by keyboard tabbing e.g. all of the navigation, "Visit the COVID-19 Page →"

![The navigation sidebar](https://user-images.githubusercontent.com/34559231/118250570-88547180-b49e-11eb-8775-40c3d4fc764e.png)

Might be related to: https://github.com/vercel/next.js/discussions/13125

**Comment by jameslittle230** [comment]
Fixed it, but I also learned that this behavior is disabled in Firefox and Safari on macOS because of a system setting??? Wild stuff. https://stackoverflow.com/a/11713537
